// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpXxeCXOdP_7XzjLUv1FzBZpp6EoQAszU',
    appId: '1:45412067411:android:c2c1b7d667d5796010bea6',
    messagingSenderId: '45412067411',
    projectId: 'todo-e233e',
    storageBucket: 'todo-e233e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApkMUvELaLn1nHHr7aoWmsvHiIfL8NyqA',
    appId: '1:45412067411:ios:361b89df3207b14310bea6',
    messagingSenderId: '45412067411',
    projectId: 'todo-e233e',
    storageBucket: 'todo-e233e.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseFirestoreTutorial',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsRgx7YOory_CB2_7Iq1dhCHXZbc1KiXU',
    appId: '1:45412067411:web:fb375354701339c410bea6',
    messagingSenderId: '45412067411',
    projectId: 'todo-e233e',
    authDomain: 'todo-e233e.firebaseapp.com',
    storageBucket: 'todo-e233e.appspot.com',
    measurementId: 'G-TN5JLSERZ6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApkMUvELaLn1nHHr7aoWmsvHiIfL8NyqA',
    appId: '1:45412067411:ios:361b89df3207b14310bea6',
    messagingSenderId: '45412067411',
    projectId: 'todo-e233e',
    storageBucket: 'todo-e233e.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseFirestoreTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsRgx7YOory_CB2_7Iq1dhCHXZbc1KiXU',
    appId: '1:45412067411:web:c644bee735793c2d10bea6',
    messagingSenderId: '45412067411',
    projectId: 'todo-e233e',
    authDomain: 'todo-e233e.firebaseapp.com',
    storageBucket: 'todo-e233e.appspot.com',
    measurementId: 'G-L17M6HS239',
  );

}